### PR TITLE
Adding spring security

### PR DESCRIPTION
**Pull request by ashwinpadmakumar**
Reg #22 
- Every user will undergo a login to user /v1 APIs
- Some users are preloaded using data.sql

Changes:
- Added User Entity to store all types of users in MySQL. 
- loadUserByUsername of UserDetailsService functionality used to build UserDetails for authentication

### CODE REVIEW

**Comment by ashwinpadmakumar** [comment]
@akhilrao2797 Rebased the branch to the latest master. If this is fine, we can proceed with adding roles in spring security

**Review by akhilrao2797 — COMMENTED** [review]
Why do we need a new controller?

**Comment by ashwinpadmakumar** [comment]
> Why do we need a new controller? @ashwinpadmakumar

@akhilrao2797 I did not add any new controller. Do you mean the new endpoint (noop)?

**Comment by akhilrao2797** [comment]
> > Why do we need a new controller? @ashwinpadmakumar
> 
> @akhilrao2797 I did not add any new controller. Do you mean the new endpoint (noop)?

Yes @ashwinpadmakumar

**Comment by ashwinpadmakumar** [comment]
> > > Why do we need a new controller? @ashwinpadmakumar
> > 
> > 
> > @akhilrao2797 I did not add any new controller. Do you mean the new endpoint (noop)?
> 
> Yes @ashwinpadmakumar

@akhilrao2797 That's no big deal. I put that just to check if we are hitting the controllers when once the user is authorized. We can remove that if not needed.

**Comment by akhilrao2797** [comment]
> > > > Why do we need a new controller? @ashwinpadmakumar
> > > 
> > > 
> > > @akhilrao2797 I did not add any new controller. Do you mean the new endpoint (noop)?
> > 
> > 
> > Yes @ashwinpadmakumar
> 
> @akhilrao2797 That's no big deal. I put that just to check if we are hitting the controllers when once the user is authorized. We can remove that if not needed.
Please remove that and update the PR

**Comment by ashwinpadmakumar** [comment]
> > > > > Why do we need a new controller? @ashwinpadmakumar
> > > > 
> > > > 
> > > > @akhilrao2797 I did not add any new controller. Do you mean the new endpoint (noop)?
> > > 
> > > 
> > > Yes @ashwinpadmakumar
> > 
> > 
> > @akhilrao2797 That's no big deal. I put that just to check if we are hitting the controllers when once the user is authorized. We can remove that if not needed.
> > Please remove that and update the PR

@akhilrao2797 Updated the PR by removing noop endpoints.

**Pull request merged**
